--- 
final_name: change-this-release-name
min_cli_version: 1.0.3
blobstore: 
  provider: s3
  options: 
    bucket_name: paas-bosh-releases
    access_key_id: AKIAI3VVLM2EK25T72VA
    secret_access_key: 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

