--- 
final_name: norouter
min_cli_version: 1.0.3
blobstore: 
  provider: s3
  options: 
    bucket_name: mah-bosh-blobs
    access_key_id: AKIAI2ALVO3UGSMF4FPA
    secret_access_key: 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

