#! /bin/bash

# Script for creating and uploading releases

if ! bosh status | egrep -q "^\s+UUID.?*335b667a-cdb2-4fc5-916e-2c6ef2c3cb51"; then
  echo "Slow down turbo! You're NOT using the dev BOSH director."
  exit 1
fi

if ! bosh status | egrep -q "^\s+Manifest.?*\/dev\/"; then
  echo "It appears you're not using a development deployment manifest."
  exit 1
fi 

set -e

BOSH_SKIP_TESTS=true bosh -n create release --force --timestamp-version
bosh -n upload release
bosh -n deploy
notify-send "Deployment completed"
